### ISSUE TITLE
Does not build on jitpack.io

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/VexRiscv#211]
Current `master` works fine, but `dev` builds has the following error:

```
[error] java.lang.RuntimeException: Invalid build URI (no handler available): file:/home/jitpack/SpinalHDL/
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$1(Load.scala:481)
[error] 	at sbt.internal.BuildLoader.$anonfun$apply$3(BuildLoader.scala:240)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:240)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid build URI (no handler available): file:/home/jitpack/SpinalHDL/
```

[full log](https://jitpack.io/com/github/SpinalHDL/VexRiscV/dev-1.0.1-g97a3c19-816/build.log). I find this intriguing, because `master` and `dev` appear to be almost the same, so perhaps one of the most recent commits broke something?

**Comment by piegamesde** [comment]
Not sure, apparently yes? Either this or JitPack previously somehow knew to clone it (as per some build instruction maybe?). Generally it would be cool to not rely too much on the directory layout of any users though.

**Comment by Dolu1990** [comment]
> Generally it would be cool to not rely too much on the directory layout of any users though.

If the structure is a issue, it can be easily changed via the build.sbt.

You would need to take the build.sbt of the master branch, update the version number, and sbt publish-local SpinalHDL dev.

**Comment by piegamesde** [comment]
Okay, so do I understand correctly that this is on the `dev` branch only and not on `master`? I didn't figure that from briefly looking at the history, they looked really similar. At least this would explain why one builds on JitPack.io and not the other.
