### ISSUE TITLE
Enabling RVC with IbusCachedPlugin causes compile failure

### ISSUE THREAD

**Issue by hpax** [SpinalHDL/VexRiscv#300]
HEAD: 2bc6e70f03edcacd875a4ec93714dc023ae136d3

How to reproduce:
Add:

        new IBusCachedPlugin(
          prediction = STATIC,
+	  compressedGen = true,
          config = InstructionCacheConfig(

... to src/main/scala/vexriscv/demo/GenFullNoMmu.scala causes a compile failure:

sbt 'runMain vexriscv.demo.GenFullNoMmu'
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/home/hpa/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.7/run_2.12-1.4.7.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] welcome to sbt 1.4.7 (Red Hat, Inc. Java 17.0.6)
[info] loading settings for project git-build from plugins.sbt ...
[info] loading project definition from /home/hpa/hwhacks/riscv/vexriscv/git/project
[info] loading settings for project root from build.sbt ...
[info] set current project to VexRiscv (in build file:/home/hpa/hwhacks/riscv/vexriscv/git/)
[info] compiling 2 Scala sources to /home/hpa/hwhacks/riscv/vexriscv/git/target/scala-2.11/classes ...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] running (fork) vexriscv.demo.GenFullNoMmu 
[info] [Runtime] SpinalHDL v1.8.0    git head : 4e3563a282582b41f4eaafc503787757251d23ea
[info] [Runtime] JVM max memory : 16056.0MiB
[info] [Runtime] Current date : 2023.02.18 19:46:28
[info] [Progress] at 0.000 : Elaborate components
[info] [Warning] This VexRiscv configuration is set without software ebreak instruction support. Some software may rely on it (ex: Rust). (This isn't related to JTAG ebreak)
[info] PcManagerSimplePlugin is now useless
[info] **********************************************************************************************
[info] [Warning] Elaboration failed (0 error).
[info]           Spinal will restart with scala trace to help you to find the problem.
[info] **********************************************************************************************
[info] [Progress] at 0.535 : Elaborate components
[info] [Warning] This VexRiscv configuration is set without software ebreak instruction support. Some software may rely on it (ex: Rust). (This isn't related to JTAG ebreak)
[info] PcManagerSimplePlugin is now useless
[error] Exception in thread "main" java.lang.Exception: Missing inserts : INSTRUCTION_ANTICIPATED
[error]         at vexriscv.Pipeline$class.build(Pipeline.scala:95)
[error]         at vexriscv.VexRiscv.build(VexRiscv.scala:123)
[error]         at vexriscv.Pipeline$$anonfun$1.apply$mcV$sp(Pipeline.scala:161)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:180)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:178)
[error]         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at spinal.core.Component.prePop(Component.scala:178)
[error]         at spinal.core.Component.postInitCallback(Component.scala:187)
[error]         at vexriscv.demo.GenFullNoMmu$.cpu(GenFullNoMmu.scala:12)
[error]         at vexriscv.demo.GenFullNoMmu$$anonfun$1.apply(GenFullNoMmu.scala:87)
[error]         at vexriscv.demo.GenFullNoMmu$$anonfun$1.apply(GenFullNoMmu.scala:87)
[error]         at spinal.core.internals.PhaseCreateComponent$$anonfun$impl$72.apply(Phase.scala:2435)
[error]         at spinal.core.fiber.Engine$$anonfun$create$1.apply$mcV$sp(AsyncCtrl.scala:147)
[error]         at spinal.core.fiber.AsyncThread$$anonfun$1.apply$mcV$sp(AsyncThread.scala:59)
[error]         at spinal.core.fiber.EngineContext$$anonfun$newJvmThread$1.apply$mcV$sp(AsyncCtrl.scala:39)
[error]         at spinal.sim.JvmThread.run(SimManager.scala:51)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 5 s, completed Feb 18, 2023, 7:46:29 PM

**Comment by hpax** [comment]
Nevermind. I see this is an FAQ.
