### ISSUE TITLE
Custom Interruptions error and Selection of the 'A' instruction set

### ISSUE THREAD

**Issue by joeljeanmonod-rgb** [SpinalHDL/VexRiscv#352]
Hi,

i have a problem with using the following custom interruption demo. 

https://github.com/SpinalHDL/VexRiscv/blob/master/src/main/scala/vexriscv/demo/GenCustomInterrupt.scala

I try build it but each time i got the following error :

```bash
[info] welcome to sbt 1.6.0 (Temurin Java 1.8.0_372)
[info] loading settings for project vexriscv-build from plugins.sbt ...
[info] loading project definition from /home/joel/TB/VexRiscv/project
[info] loading settings for project root from build.sbt ...
[info] set current project to VexRiscv (in build file:/home/joel/TB/VexRiscv/)
[info] running (fork) vexriscv.demo.GenCustomInterrupt 
[info] [Runtime] SpinalHDL v1.8.1    git head : 2a7592004363e5b40ec43e1f122ed8641cd8965b
[info] [Runtime] JVM max memory : 7111.5MiB
[info] [Runtime] Current date : 2023.07.01 17:29:37
[info] [Progress] at 0.000 : Elaborate components
[info] ERROR !
[info] A null pointer access has been detected in the JVM.
[info] This could happen when in your SpinalHDL description, you access an signal which is only defined further.
[error] Exception in thread "main" java.lang.NullPointerException
[info] For instance :
[error]         at vexriscv.plugin.CsrPlugin.r(CsrPlugin.scala:534)
[error]         at vexriscv.plugin.UserInterruptPlugin.setup(CsrPlugin.scala:1743)
[error]         at vexriscv.plugin.UserInterruptPlugin.setup(CsrPlugin.scala:1735)
[info]   val result = Bool()
[error]         at vexriscv.Pipeline$$anonfun$build$2.apply(Pipeline.scala:47)
[error]         at vexriscv.Pipeline$$anonfun$build$2.apply(Pipeline.scala:47)
[error]         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   result := a ^ b  //a and b can't be accessed there because they are only defined one line below (Software rule of execution order)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at vexriscv.Pipeline$class.build(Pipeline.scala:47)
[info]   val a,b = Bool()
[info]           
[error]         at vexriscv.VexRiscv.build(VexRiscv.scala:126)
[error]         at vexriscv.Pipeline$$anonfun$1.apply$mcV$sp(Pipeline.scala:161)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:180)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:178)
[error]         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at spinal.core.Component.prePop(Component.scala:178)
[error]         at spinal.core.Component.postInitCallback(Component.scala:187)
[error]         at vexriscv.demo.GenCustomInterrupt$.cpu(GenCustomInterrupt.scala:11)
[error]         at vexriscv.demo.GenCustomInterrupt$$anonfun$1.apply(GenCustomInterrupt.scala:71)
[error]         at vexriscv.demo.GenCustomInterrupt$$anonfun$1.apply(GenCustomInterrupt.scala:71)
[error]         at spinal.core.internals.PhaseCreateComponent$$anonfun$impl$66.apply(Phase.scala:2564)
[error]         at spinal.core.fiber.Engine$$anonfun$create$1.apply$mcV$sp(AsyncCtrl.scala:147)
[error]         at spinal.core.fiber.AsyncThread$$anonfun$1.apply$mcV$sp(AsyncThread.scala:59)
[error]         at spinal.core.fiber.EngineContext$$anonfun$newJvmThread$1.apply$mcV$sp(AsyncCtrl.scala:39)
[error]         at spinal.sim.JvmThread.run(SimManager.scala:51)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed Jul 1, 2023 5:29:37 PM
```

My main goal is to add 32 custom interruptions that i can freely connect to peripherals like GPIO for example.
I have the following VexRISCV configuration :

```scala
package vexriscv.demo
import vexriscv.plugin._
import vexriscv.ip.{DataCacheConfig, InstructionCacheConfig}
import vexriscv.{plugin, VexRiscv, VexRiscvConfig}
import spinal.core._
import spinal.lib.bus.amba4.axi.Axi4ReadOnly
import vexriscv.ip.fpu.FpuParameter

import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba4.axi.Axi4ReadOnly
import spinal.lib.bus.avalon.AvalonMM
import spinal.lib.com.jtag.Jtag
import spinal.lib.com.jtag.JtagTapInstructionCtrl
import spinal.lib.eda.altera.{InterruptReceiverTag, QSysify, ResetEmitterTag}
import vexriscv.ip.{DataCacheConfig, InstructionCacheConfig}
import vexriscv.plugin._
import vexriscv.{VexRiscv, VexRiscvConfig, plugin}

object GenSignate{
    def main(args: Array[String]) {
        val report = SpinalVerilog{
            val cpuConfig = VexRiscvConfig(
                plugins = List(
                    new IBusCachedPlugin(
                        resetVector = 0x80000000l,
                        prediction = DYNAMIC_TARGET,
                        historyRamSizeLog2 = 8,
                            config = InstructionCacheConfig(
                            cacheSize = 4096,
                            bytePerLine = 32,
                            wayCount = 1,
                            addressWidth = 32,
                            cpuDataWidth = 32,
                            memDataWidth = 32,
                            catchIllegalAccess = true,
                            catchAccessFault = true,
                            asyncTagMemory = false,
                            twoCycleRam = true,
                            twoCycleCache = true
                            )
                    ),
                    new DBusCachedPlugin(
                            config = new DataCacheConfig(
                            cacheSize        = 4096,
                            bytePerLine      = 32,
                            wayCount         = 1,
                            addressWidth     = 32,
                            cpuDataWidth     = 32,
                            memDataWidth     = 32,
                            catchAccessError = true,
                            catchIllegal     = true,
                            catchUnaligned   = true
                        )
                    ),
                    new StaticMemoryTranslatorPlugin(
                        ioRange = _(31 downto 28) === 0xF
                    ),
                    new DecoderSimplePlugin(
                        catchIllegalInstruction = true
                    ),
                    new RegFilePlugin(
                        regFileReadyKind = plugin.SYNC,
                        zeroBoot = false
                    ),
                    new IntAluPlugin,
                    new SrcPlugin(
                        separatedAddSub = false,
                        executeInsertion = true
                    ),
                    new FullBarrelShifterPlugin,
                    new HazardSimplePlugin(
                        bypassExecute = true,
                        bypassMemory = true,
                        bypassWriteBack = true,
                        bypassWriteBackBuffer = true,
                        pessimisticUseSrc = false,
                        pessimisticWriteRegFile = false,
                        pessimisticAddressMatch = false
                    ),
                    new MulPlugin,
                    new DivPlugin,
                    new CsrPlugin(CsrPluginConfig.small),
                    new DebugPlugin(ClockDomain.current.copy(reset = Bool().setName("debugReset"))),
                    new BranchPlugin(
                        earlyBranch = false,
                        catchAddressMisaligned = true
                    ),
                    new YamlPlugin("cpu0.yaml")
                )
            )
            // SpinalVerilog(cpu())
            //CPU instanciation
            val cpu = new VexRiscv(cpuConfig)
            // val cpu = SpinalVerilog(cpu())
            //CPU modifications to be an Avalon one
            cpu.setDefinitionName("VexRiscvSignate")
            cpu.rework {
                var iBus : Axi4ReadOnly = null
                for (plugin <- cpuConfig.plugins) plugin match {
                    case plugin: IBusSimplePlugin => {
                    plugin.iBus.setAsDirectionLess() //Unset IO properties of iBus
                    iBus = master(plugin.iBus.toAxi4ReadOnly().toFullConfig())
                    // iBus = master(plugin.iBus.toAxi4ReadOnly())
                        .setName("iBusAxi")
                        .addTag(ClockDomainTag(ClockDomain.current)) //Specify a clock domain to the iBus (used by QSysify)
                    }
                    case plugin: IBusCachedPlugin => {
                    plugin.iBus.setAsDirectionLess() //Unset IO properties of iBus
                    iBus = master(plugin.iBus.toAxi4ReadOnly().toFullConfig())
                    // iBus = master(plugin.iBus.toAxi4ReadOnly())
                        .setName("iBusAxi")
                        .addTag(ClockDomainTag(ClockDomain.current)) //Specify a clock domain to the iBus (used by QSysify)
                    }
                    case plugin: DBusSimplePlugin => {
                    plugin.dBus.setAsDirectionLess()
                    master(plugin.dBus.toAxi4Shared().toAxi4().toFullConfig())
                    // master(plugin.dBus.toAxi4Shared().toAxi4())
                        .setName("dBusAxi")
                        .addTag(ClockDomainTag(ClockDomain.current))
                    }
                    case plugin: DBusCachedPlugin => {
                    plugin.dBus.setAsDirectionLess()
                    master(plugin.dBus.toAxi4Shared().toAxi4().toFullConfig())
                    // master(plugin.dBus.toAxi4Shared().toAxi4())
                        .setName("dBusAxi")
                        .addTag(ClockDomainTag(ClockDomain.current))
                    }
                    case plugin: DebugPlugin => plugin.debugClockDomain {
                    plugin.io.bus.setAsDirectionLess()
                    //BSCANE2 JTAG
                    val jtagCtrl = JtagTapInstructionCtrl()
                    val tap = jtagCtrl.fromXilinxBscane2(userId = 2)
                    jtagCtrl <> plugin.io.bus.fromJtagInstructionCtrl(ClockDomain(tap.TCK), 0)
                    plugin.io.resetOut
                      .addTag(ResetEmitterTag(plugin.debugClockDomain))
                      .parent = null //Avoid the io bundle to be interpreted as a QSys conduit
                    }
                    case _ =>
                }
                for (plugin <- cpuConfig.plugins) plugin match {
                    case plugin: CsrPlugin => {
                    plugin.externalInterrupt
                        .addTag(InterruptReceiverTag(iBus, ClockDomain.current))
                    plugin.timerInterrupt
                        .addTag(InterruptReceiverTag(iBus, ClockDomain.current))
                    }
                    case _ =>
                }
            }
            cpu
        }
    }
}
```

My question is how i can do this ?

I have second  question. How can you choose to enable or not the 'A' instructions set ?

Thank you in advance for any help you can provide.

**Comment by Dolu1990** [comment]
Hi ^^

Sorry for the delay i was AFK holiday XD

So, i pushed a fix for the GenCustomInterrupt demo via https://github.com/SpinalHDL/VexRiscv/commit/1746af1cfe11d0f75b6d3b4460c7d4a0ff8cf98f

(just have to have the CsrPlugin first in the list, that's not great, i would say even a bit flawed, but hooo well XD)

> I have second question. How can you choose to enable or not the 'A' instructions set ?

If you don't have memory coherency, you just need to turn on in the DataCacheConfig the following parameters : 
                           withLrSc = true
                           withAmo = true

Note that the atomic stay in the CPU, if you have another memory master it wont be atomic with that other memory master
