### ISSUE TITLE
Combinatorial loop with AhbLite3Decoder

### ISSUE THREAD

**Issue by patstew** [SpinalHDL/VexRiscv#376]
If I connect the VexRiscV to a AhbLite3Decoder from SpinalHDL I get a combinatorial loop.

```
package vexriscv.demo


import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba3.ahblite._
import vexriscv.plugin._
import vexriscv.{VexRiscv, VexRiscvConfig, plugin}

class AHBTest() extends Component{
  //CPU configuration
  val cpuConfig = VexRiscvConfig(
    plugins = List(
      new IBusSimplePlugin(
        resetVector = 0x80000000l,
        cmdForkOnSecondStage = false,
        cmdForkPersistence = true,
        prediction = STATIC,
        catchAccessFault = false,
        compressedGen = false
      ),
      new DBusSimplePlugin(
        catchAddressMisaligned = false,
        catchAccessFault = false
      ),
      new StaticMemoryTranslatorPlugin(
        ioRange      = _(31 downto 28) === 0xF
      ),
      new DecoderSimplePlugin(
        catchIllegalInstruction = true
      ),
      new RegFilePlugin(
        regFileReadyKind = plugin.SYNC,
        zeroBoot = false
      ),
      new IntAluPlugin,
      new SrcPlugin(
        separatedAddSub = false,
        executeInsertion = true
      ),
      new FullBarrelShifterPlugin,
      new MulPlugin,
      new DivPlugin,
      new HazardSimplePlugin(
        bypassExecute           = true,
        bypassMemory            = true,
        bypassWriteBack         = true,
        bypassWriteBackBuffer   = true,
        pessimisticUseSrc       = false,
        pessimisticWriteRegFile = false,
        pessimisticAddressMatch = false
      ),
      new DebugPlugin(ClockDomain.current.clone(reset = Bool().setName("debugReset"))),
      new BranchPlugin(
        earlyBranch = false,
        catchAddressMisaligned = true
      ),
      new CsrPlugin(
        config = CsrPluginConfig(
          catchIllegalAccess = false,
          mvendorid      = null,
          marchid        = null,
          mimpid         = null,
          mhartid        = null,
          misaExtensionsInit = 66,
          misaAccess     = CsrAccess.NONE,
          mtvecAccess    = CsrAccess.NONE,
          mtvecInit      = 0x00000020l,
          mepcAccess     = CsrAccess.READ_WRITE,
          mscratchGen    = false,
          mcauseAccess   = CsrAccess.READ_ONLY,
          mbadaddrAccess = CsrAccess.READ_ONLY,
          mcycleAccess   = CsrAccess.NONE,
          minstretAccess = CsrAccess.NONE,
          ecallGen       = false,
          wfiGenAsWait         = false,
          ucycleAccess   = CsrAccess.NONE,
          uinstretAccess = CsrAccess.NONE
        )
      ),
      new YamlPlugin("cpu0.yaml")
    )
  )

  //CPU instanciation
  val cpu = new VexRiscv(cpuConfig)
  var ibus : AhbLite3 = null
  var dbus : AhbLite3 = null

    //Checkout plugins used to instanciate the CPU to connect them to the SoC
    for(plugin <- cpu.plugins) plugin match{
      case plugin : IBusSimplePlugin =>
        ibus = plugin.iBus.toAhbLite3Master().toAhbLite3()
      case plugin : DBusSimplePlugin =>
        dbus = plugin.dBus.toAhbLite3Master(true).toAhbLite3()
      case _ =>
    }

  val ram = AhbLite3OnChipRam(AhbLite3Config(32, 32), 16 kB)

  val dbusdecoder = AhbLite3Decoder(
              master = dbus,
              slaves = List(
                    ram.io.ahb -> (0x10000000, 16 kB)
              ))
}

object VexRiscvAhbLite3{
  def main(args: Array[String]) {
    SpinalVerilog(new AHBTest())
  }
}
```

```
[error] COMBINATORIAL LOOP :
[error]   Partial chain :
[error]     >>> (toplevel/??? :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3Master.<init>(AhbLite3.scala:68) >>>
[error]     >>> (toplevel/cpu/dBus_rsp_ready : in Bool) at vexriscv.plugin.DBusSimpleRsp.<init>(DBusSimplePlugin.scala:25) >>>
[error]     >>> (toplevel/cpu/when_DBusSimplePlugin_l489 :  Bool) at vexriscv.plugin.DBusSimplePlugin$$anon$6.<init>(DBusSimplePlugin.scala:489) >>>
[error]     >>> (toplevel/cpu/memory_arbitration_haltItself :  Bool) at vexriscv.Stage$$anon$1.<init>(Stage.scala:49) >>>
[error]     >>> (toplevel/cpu/memory_arbitration_isStuck :  Bool) at vexriscv.Stage$$anon$1.<init>(Stage.scala:55) >>>
[error]     >>> (toplevel/cpu/execute_arbitration_isStuckByOthers :  Bool) at vexriscv.Stage$$anon$1.<init>(Stage.scala:56) >>>
[error]     >>> (toplevel/cpu/dBus_cmd_valid : out Bool) at spinal.lib.Stream.<init>(Stream.scala:55) >>>
[error]     >>> (toplevel/??? :  Bits[2 bits]) at spinal.lib.bus.amba3.ahblite.AhbLite3Master.<init>(AhbLite3.scala:60) >>>
[error]     >>> (toplevel/dbusdecoder/io_input_HTRANS : in Bits[2 bits]) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:115) >>>
[error]     >>> (toplevel/dbusdecoder/isIdle :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.isIdle(AhbLite3.scala:136) >>>
[error]     >>> (toplevel/dbusdecoder/decodesSlaves :  Bits[1 bits]) at spinal.lib.TraversableOncePimped.asBits(Utils.scala:1158) >>>
[error]     >>> (toplevel/dbusdecoder/decodeDefaultSlave :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3Decoder.<init>(AhbLite3Decoder.scala:156) >>>
[error]     >>> (toplevel/dbusdecoder/decodedSels :  Bits[2 bits]) at spinal.lib.bus.amba3.ahblite.AhbLite3Decoder.<init>(AhbLite3Decoder.scala:158) >>>
[error]     >>> (toplevel/dbusdecoder/noneIdleSwitchDetected :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3Decoder.<init>(AhbLite3Decoder.scala:163) >>>
[error]     >>> (toplevel/dbusdecoder/applyedSels :  Bits[2 bits]) at spinal.lib.bus.amba3.ahblite.AhbLite3Decoder.<init>(AhbLite3Decoder.scala:159) >>>
[error]     >>> (toplevel/dbusdecoder/io_outputs_0_HSEL : out Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:109) >>>
[error]     >>> (toplevel/ram/io_ahb_HSEL : in Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:109) >>>
[error]     >>> (toplevel/ram/io_ahb_HREADYOUT : out Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:123) >>>
[error]     >>> (toplevel/dbusdecoder/io_outputs_0_HREADYOUT : in Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:123) >>>
[error]     >>> (toplevel/dbusdecoder/slaveReadyOutReduction :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3Decoder$$anonfun$8.apply(AhbLite3Decoder.scala:153) >>>
[error]     >>> (toplevel/dbusdecoder/io_input_HREADYOUT : out Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:123) >>>
[error]     >>> (toplevel/??? :  Bool) at spinal.lib.bus.amba3.ahblite.AhbLite3.<init>(AhbLite3.scala:123) >>>
[error]   Full chain :
[error]     (toplevel/??? :  Bool)
[error]     Bool && Bool
[error]     (toplevel/cpu/dBus_rsp_ready : in Bool)
[error]     ! Bool
[error]     Bool || Bool
[error]     Bool && Bool
[error]     (toplevel/cpu/when_DBusSimplePlugin_l489 :  Bool)
[error]     spinal.core.internals.WhenStatement@154bd49b
[error]     (toplevel/cpu/memory_arbitration_haltItself :  Bool)
[error]     Bool || Bool
[error]     (toplevel/cpu/memory_arbitration_isStuck :  Bool)
[error]     Bool || Bool
[error]     Bool || Bool
[error]     Bool || Bool
[error]     (toplevel/cpu/execute_arbitration_isStuckByOthers :  Bool)
[error]     ! Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     (toplevel/cpu/dBus_cmd_valid : out Bool)
[error]     Bits -> Bits
[error]     Bits ## Bits
[error]     (toplevel/??? :  Bits[2 bits])
[error]     (toplevel/dbusdecoder/io_input_HTRANS : in Bits[2 bits])
[error]     Bits === Bits
[error]     (toplevel/dbusdecoder/isIdle :  Bool)
[error]     ! Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     Bits -> Bits
[error]     (toplevel/dbusdecoder/decodesSlaves :  Bits[1 bits])
[error]     Bits === Bits
[error]     Bool && Bool
[error]     Bool && Bool
[error]     (toplevel/dbusdecoder/decodeDefaultSlave :  Bool)
[error]     Bits -> Bits
[error]     Bits ## Bits
[error]     (toplevel/dbusdecoder/decodedSels :  Bits[2 bits])
[error]     Bits =/= Bits
[error]     Bool && Bool
[error]     Bool && Bool
[error]     (toplevel/dbusdecoder/noneIdleSwitchDetected :  Bool)
[error]     ! Bool
[error]     (Bool ? Bits | Bits)[2 bits]
[error]     (toplevel/dbusdecoder/applyedSels :  Bits[2 bits])
[error]     Bits(Int)
[error]     (toplevel/dbusdecoder/io_outputs_0_HSEL : out Bool)
[error]     (toplevel/ram/io_ahb_HSEL : in Bool)
[error]     Bool && Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     Bool && Bool
[error]     ! Bool
[error]     (toplevel/ram/io_ahb_HREADYOUT : out Bool)
[error]     (toplevel/dbusdecoder/io_outputs_0_HREADYOUT : in Bool)
[error]     Bool && Bool
[error]     (toplevel/dbusdecoder/slaveReadyOutReduction :  Bool)
[error]     Bool && Bool
[error]     (toplevel/dbusdecoder/io_input_HREADYOUT : out Bool)
[error]     (toplevel/??? :  Bool)
[error] ********************************************************************************
```

**Comment by Dolu1990** [comment]
Hi ^^
I pushed a fix which avoid the combinatorial loop

```scala
import spinal.core._
import spinal.lib._
import spinal.lib.bus.amba3.ahblite._
import vexriscv.plugin._
import vexriscv.{VexRiscv, VexRiscvConfig, plugin}

class AHBTest() extends Component{
  //CPU configuration
  val cpuConfig = VexRiscvConfig(
    plugins = List(
      new IBusSimplePlugin(
        resetVector = 0x80000000l,
        cmdForkOnSecondStage = false,
        cmdForkPersistence = true,
        prediction = STATIC,
        catchAccessFault = false,
        compressedGen = false
      ),
      new DBusSimplePlugin(
        catchAddressMisaligned = false,
        catchAccessFault = false
      ),
      new StaticMemoryTranslatorPlugin(
        ioRange      = _(31 downto 28) === 0xF
      ),
      new DecoderSimplePlugin(
        catchIllegalInstruction = true
      ),
      new RegFilePlugin(
        regFileReadyKind = plugin.SYNC,
        zeroBoot = false
      ),
      new IntAluPlugin,
      new SrcPlugin(
        separatedAddSub = false,
        executeInsertion = true
      ),
      new FullBarrelShifterPlugin,
      new MulPlugin,
      new DivPlugin,
      new HazardSimplePlugin(
        bypassExecute           = true,
        bypassMemory            = true,
        bypassWriteBack         = true,
        bypassWriteBackBuffer   = true,
        pessimisticUseSrc       = false,
        pessimisticWriteRegFile = false,
        pessimisticAddressMatch = false
      ),
      new DebugPlugin(ClockDomain.current.clone(reset = Bool().setName("debugReset"))),
      new BranchPlugin(
        earlyBranch = false,
        catchAddressMisaligned = true
      ),
      new CsrPlugin(
        config = CsrPluginConfig(
          catchIllegalAccess = false,
          mvendorid      = null,
          marchid        = null,
          mimpid         = null,
          mhartid        = null,
          misaExtensionsInit = 66,
          misaAccess     = CsrAccess.NONE,
          mtvecAccess    = CsrAccess.NONE,
          mtvecInit      = 0x00000020l,
          mepcAccess     = CsrAccess.READ_WRITE,
          mscratchGen    = false,
          mcauseAccess   = CsrAccess.READ_ONLY,
          mbadaddrAccess = CsrAccess.READ_ONLY,
          mcycleAccess   = CsrAccess.NONE,
          minstretAccess = CsrAccess.NONE,
          ecallGen       = false,
          wfiGenAsWait   = false,
          ucycleAccess   = CsrAccess.NONE,
          uinstretAccess = CsrAccess.NONE
        )
      ),
      new YamlPlugin("cpu0.yaml")
    )
  )

  //CPU instanciation
  val cpu = new VexRiscv(cpuConfig)
  var ibus : AhbLite3 = null
  var dbus : AhbLite3 = null

  //Checkout plugins used to instanciate the CPU to connect them to the SoC
  for(plugin <- cpu.plugins) plugin match{
    case plugin : IBusSimplePlugin =>
      ibus = master(plugin.iBus.toAhbLite3Master().toAhbLite3())
    case plugin : DBusSimplePlugin =>
      dbus = (plugin.dBus.toAhbLite3Master(true).toAhbLite3())
    case plugin: DebugPlugin => plugin.debugClockDomain {
      val jtag = slave(new Jtag()).setName("jtag")
      jtag <> plugin.io.bus.fromJtag()
      in(plugin.debugClockDomain.reset)
    }
    case plugin : CsrPlugin => {
      plugin.timerInterrupt.toIo()
      plugin.externalInterrupt.toIo()
    }
    case _ =>
  }

  val ram = AhbLite3OnChipRam(AhbLite3Config(32, 32), 16 kB)

  val dbusdecoder = AhbLite3Decoder(
    master = dbus,
    slaves = List(
      ram.io.ahb -> (0x10000000, 16 kB)
    ))
}

object VexRiscvAhbLite3{
  def main(args: Array[String]) {
    SpinalVerilog(new AHBTest())
  }
}
```
