### ISSUE TITLE
GenFullWithOfficialRiscvDebug failed

### ISSUE THREAD

**Issue by Logiase** [SpinalHDL/VexRiscv#421]
demo `GenFullWithOfficialRiscvDebug` can not run.

```text
[info] running (fork) "vexriscv.demo.GenFullWithOfficialRiscvDebug"
[info] [Runtime] SpinalHDL v1.10.2a    git head : a348a60b7e8b6a455c72e1536ec3d74a2ea16935
[info] [Runtime] JVM max memory : 16168.0MiB
[info] [Runtime] Current date : 2024.08.17 14:44:57
[info] [Progress] at 0.000 : Elaborate components
[info] vexriscv.plugin.CsrPlugin$$anonfun$47$$anon$2.<init>(CsrPlugin.scala:719)
[info] vexriscv.plugin.CsrPlugin$$anonfun$47.apply(CsrPlugin.scala:702)
[info] vexriscv.plugin.CsrPlugin$$anonfun$47.apply(CsrPlugin.scala:702)
[info] spinal.core.internals.BooleanPimped.generate(Misc.scala:285)
[info] vexriscv.plugin.CsrPlugin.build(CsrPlugin.scala:702)
[info] vexriscv.plugin.CsrPlugin.build(CsrPlugin.scala:445)
[info] vexriscv.Pipeline$$anonfun$build$4.apply(Pipeline.scala:55)
[info] vexriscv.Pipeline$$anonfun$build$4.apply(Pipeline.scala:55)
[info] scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info] scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info] vexriscv.Pipeline$class.build(Pipeline.scala:55)
[info] vexriscv.VexRiscv.build(VexRiscv.scala:131)
[info] vexriscv.Pipeline$$anonfun$1.apply$mcV$sp(Pipeline.scala:161)
[info] spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:187)
[info] spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:185)
[info] scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info] scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info] spinal.core.Component.prePop(Component.scala:185)
[info] spinal.core.Component.postInitCallback(Component.scala:194)
[info] vexriscv.demo.GenFullWithOfficialRiscvDebug$.cpu(GenFullWithOfficialRiscvDebug.scala:125)
[info] vexriscv.demo.GenFullWithOfficialRiscvDebug$$anonfun$3.apply(GenFullWithOfficialRiscvDebug.scala:127)
[info] vexriscv.demo.GenFullWithOfficialRiscvDebug$$anonfun$3.apply(GenFullWithOfficialRiscvDebug.scala:127)
[info] spinal.core.internals.PhaseCreateComponent$$anonfun$impl$67.apply(Phase.scala:2561)
[info] spinal.core.fiber.Engine$$anonfun$create$1.apply$mcV$sp(AsyncCtrl.scala:173)
[info] spinal.core.fiber.AsyncThread$$anonfun$1.apply$mcV$sp(AsyncThread.scala:60)
[info] spinal.core.fiber.EngineContext$$anonfun$newJvmThread$1.apply$mcV$sp(AsyncCtrl.scala:39)
[info] spinal.sim.JvmThread.run(SimManager.scala:51)
[info] **********************************************************************************************
[info] [Warning] Elaboration failed (0 error).
[info]           Spinal will restart with scala trace to help you to find the problem.
[info] **********************************************************************************************
[info] [Progress] at 1.211 : Elaborate components
[error] Exception in thread "main" java.lang.NoSuchMethodError: 'spinal.core.Data spinal.lib.BufferCC$.apply(spinal.core.Data, scala.Function0, scala.Option, boolean)'
[error]         at vexriscv.plugin.CsrPlugin$$anonfun$47$$anon$2.<init>(CsrPlugin.scala:719)
[error]         at vexriscv.plugin.CsrPlugin$$anonfun$47.apply(CsrPlugin.scala:702)
[error]         at vexriscv.plugin.CsrPlugin$$anonfun$47.apply(CsrPlugin.scala:702)
[error]         at spinal.core.internals.BooleanPimped.generate(Misc.scala:285)
[error]         at vexriscv.plugin.CsrPlugin.build(CsrPlugin.scala:702)
[error]         at vexriscv.plugin.CsrPlugin.build(CsrPlugin.scala:445)
[error]         at vexriscv.Pipeline$$anonfun$build$4.apply(Pipeline.scala:55)
[error]         at vexriscv.Pipeline$$anonfun$build$4.apply(Pipeline.scala:55)
[error]         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at vexriscv.Pipeline$class.build(Pipeline.scala:55)
[error]         at vexriscv.VexRiscv.build(VexRiscv.scala:131)
[error]         at vexriscv.Pipeline$$anonfun$1.apply$mcV$sp(Pipeline.scala:161)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:187)
[error]         at spinal.core.Component$$anonfun$prePop$1.apply(Component.scala:185)
[error]         at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error]         at spinal.core.Component.prePop(Component.scala:185)
[error]         at spinal.core.Component.postInitCallback(Component.scala:194)
[error]         at vexriscv.demo.GenFullWithOfficialRiscvDebug$.cpu(GenFullWithOfficialRiscvDebug.scala:125)
[error]         at vexriscv.demo.GenFullWithOfficialRiscvDebug$$anonfun$3.apply(GenFullWithOfficialRiscvDebug.scala:127)
[error]         at vexriscv.demo.GenFullWithOfficialRiscvDebug$$anonfun$3.apply(GenFullWithOfficialRiscvDebug.scala:127)
[error]         at spinal.core.internals.PhaseCreateComponent$$anonfun$impl$67.apply(Phase.scala:2561)
[error]         at spinal.core.fiber.Engine$$anonfun$create$1.apply$mcV$sp(AsyncCtrl.scala:173)
[error]         at spinal.core.fiber.AsyncThread$$anonfun$1.apply$mcV$sp(AsyncThread.scala:60)
[error]         at spinal.core.fiber.EngineContext$$anonfun$newJvmThread$1.apply$mcV$sp(AsyncCtrl.scala:39)
[error]         at spinal.sim.JvmThread.run(SimManager.scala:51)
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
```

**Comment by Logiase** [comment]
Sorry, change spinalhdl version to 1.10.1 fix this.
